sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ilhom7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ilhom7/docker-react npm run test
